### ISSUE TITLE
a test issue

### ISSUE THREAD

**Issue by heycam** [heycam/rubbish#2]
Resolutions were made for [csswg-drafts/#3769](https://github.com./w3c/csswg-drafts/issues/3769).

**Is the list-item counter increment for list items reflected in the computed style?**

* `RESOLVED: implicit list-item counter is not reflected in computed style`

[Discussion.](https://github.com./w3c/csswg-drafts/issues/3769#issuecomment-481773323)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
update

**Comment by heycam** [comment]
update

**Comment by heycam** [comment]
update

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1547188

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1547189
